name: finetune 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - fastapi
  - flask
  - uvicorn
  - grpcio
  - sqlalchemy
  - jinja2
  - pyarrow
  - protobuf
  - google-auth
  - transformers
  - tensorboardx
  - pillow
  - pyyaml
  - tqdm
  - requests
  - rich
  - sympy
  - pip:
      - aiohttp==3.9.4
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - alembic==1.13.1
      - aniso8601==9.0.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - blinker==1.7.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorful==0.5.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - distlib==0.3.8
      - docker==7.0.0
      - entrypoints==0.4
      - exceptiongroup==1.2.0
      - filelock==3.13.4
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - GitPython==3.1.43
      - google-api-core==2.18.0
      - googleapis-common-protos==1.63.0
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - gunicorn==21.2.0
      - h11==0.14.0
      - httptools==0.6.1
      - huggingface-hub==0.22.2
      - idna==3.7
      - importlib_metadata==7.1.0
      - itsdangerous==2.1.2
      - joblib==1.4.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lightning==2.2.1
      - lightning-utilities==0.11.2
      - Mako==1.3.3
      - Markdown==3.6
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.5
      - mdurl==0.1.2
      - mlflow==2.11.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - networkx==3.3
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - packaging==23.2
      - platformdirs==4.2.0
      - prometheus_client==0.20.0
      - proto-plus==1.23.0
      - py-spy==0.3.14
      - pyasn1==0.6.0
      - pyasn1_modules==0.4.0
      - pydantic==2.7.0
      - pydantic_core==2.18.1
      - Pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - querystring-parser==1.2.4
      - ray==2.10.0
      - referencing==0.34.0
      - regex==2023.12.25
      - rpds-py==0.18.0
      - rsa==4.9
      - safetensors==0.4.2
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlparse==0.4.4
      - starlette==0.37.2
      - threadpoolctl==3.4.0
      - tokenizers==0.15.2
      - torchmetrics==1.3.2
      - typer==0.12.3
      - typing_extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvloop==0.19.0
      - virtualenv==20.25.1
      - watchfiles==0.21.0
      - websockets==12.0
      - Werkzeug==3.0.2
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.18.1



# triton == 2.2.0